<?php namespace Peteleco\Buzzlead\Test;

use Faker\Generator;
use Orchestra\Testbench\TestCase as Orchestra;
use Peteleco\Buzzlead\Api\ConversionRequest;
use Peteleco\Buzzlead\Api\CreateAmbassadorRequest;
use Peteleco\Buzzlead\Model\OrderForm;
use Peteleco\Buzzlead\Model\SourceForm;

/**
 * Class TestCase
 *
 * @package Peteleco\Buzzlead\Test
 */
abstract class TestCase extends Orchestra
{

    /**
     * @var Generator
     */
    public $faker;

    /**
     *
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->faker = \Faker\Factory::create();
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            \Peteleco\Buzzlead\BuzzleadServiceProvider::class,
        ];
    }

    /**
     * Cria um embaixador e retona o voucher id
     *
     * @return mixed
     */
    protected function createAmbassador(): string
    {
        $api = new CreateAmbassadorRequest($this->config['buzzlead']);

        $api->setSourceForm($sourceForm = new SourceForm([
            'name'  => $this->faker->name(),
            'email' => $this->faker->email()
        ]));

        $response = $api->send();

        return $response->getVoucher();
    }

    public function createConversion($voucher)
    {
        $api = new ConversionRequest($this->config['buzzlead']);
        $api->setOrderForm(new OrderForm([
            'codigo' => $voucher,
            'pedido' => $orderId = $this->faker->uuid,
            'total'  => 151.10,
            'nome'   => $this->faker->name,
            'email'  => $this->faker->email,
        ]));
        $api->send();
        return $orderId;
    }
}