<?php namespace Peteleco\Buzzlead\Test;

use Faker\Generator;
use Orchestra\Testbench\TestCase as Orchestra;

/**
 * Class TestCase
 *
 * @package Peteleco\Buzzlead\Test
 */
abstract class TestCase extends Orchestra
{

    /**
     * @var Generator
     */
    public $faker;

    /**
     *
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->faker = \Faker\Factory::create();
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            \Peteleco\Buzzlead\BuzzleadServiceProvider::class,
        ];
    }
}